#!/bin/bash
exec 2>&1

cd {{pkg.svc_data_path}}/app/
source venv/bin/activate
{{#if cfg.http.listen.local_only ~}}
venv/bin/gunicorn --bind {{cfg.http.listen.bind}}:{{cfg.http.listen.port}} --worker-class gevent --workers 2 --max-requests 1000 requestbin:app
{{else ~}}
venv/bin/gunicorn --bind {{cfg.http.listen.bind}}:{{cfg.http.listen.port}} --worker-class gevent --workers 2 --max-requests 1000 requestbin:app
{{/if ~}}

